name: Build/release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: checkout v2
        uses: actions/checkout@v2

      - name: Install Node.js, NPM
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install rpm if necessary
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install rpm

      - name: Install packages
        working-directory: ./app
        run: npm install

      - name: Install Renderer Packages
        working-directory: ./app/src/renderer
        run: npm install

      - name: Publish Build to Github
        working-directory: ./app
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
